# golangci-lint configuration for HyperFleet Pull Secret Job
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet          # Reports suspicious constructs
    - errcheck       # Checks for unchecked errors
    - staticcheck    # Static analysis checks
    - unused         # Checks for unused constants, variables, functions and types
    - ineffassign    # Detects ineffectual assignments
    - misspell       # Finds commonly misspelled English words
    - revive         # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - gocritic       # Provides diagnostics that check for bugs, performance and style issues

formatters:
  enable:
    - gofmt          # Checks whether code was gofmt-ed
    - goimports      # Checks import statements are formatted according to the 'goimport' command

linters-settings:

  govet:
    enable:
      - shadow
    disable:
      - check-shadowing

  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true  # Disabled for MVP - can enable later
      - name: unexported-return
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

output:
  formats:
    stdout: colored-line-number
  print-issued-lines: true
  print-linter-name: true
